# -*- coding: utf-8 -*-
"""Demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19OhVJ6sJVXJEtpRfefLA81_s8CSVfL8O
"""

import cv2
from pcos_system import PCOSProductionSystem

system = PCOSProductionSystem(base_dir="..")

img = cv2.imread("test_image.jpg")
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

result = system.diagnose_from_array(img)

print(result)