# -*- coding: utf-8 -*-
"""Demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19OhVJ6sJVXJEtpRfefLA81_s8CSVfL8O
"""

"""
NeuLogic-PCOS  —  Run diagnosis from terminal
"""

import os
import sys
import cv2
import numpy as np
import matplotlib.pyplot as plt
import tkinter as tk
from tkinter import filedialog

# ============================================================
# 1. File picker  —  select your ultrasound image
# ============================================================

root = tk.Tk()
root.withdraw()

IMAGE_PATH = filedialog.askopenfilename(
    title="Select an ultrasound image",
    filetypes=[
        ("Image files", "*.jpg *.jpeg *.png *.bmp"),
        ("All files", "*.*")
    ]
)

root.destroy()

if not IMAGE_PATH:
    print("No file selected. Exiting.")
    sys.exit()

# Load image
image = cv2.imread(IMAGE_PATH)
if image is None:
    print(f"Could not read image: {IMAGE_PATH}")
    sys.exit()

image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
print(f"\n Image loaded: {IMAGE_PATH}")
print(f" Shape: {image.shape}")

# ============================================================
# 2. Load the production system
# ============================================================

from pcos_system import PCOSProductionSystem
system = PCOSProductionSystem(model_dir="models")

# ============================================================
# 3. Run diagnosis
# ============================================================

print("\n" + "=" * 70)
print("RUNNING DIAGNOSIS")
print("=" * 70)

result = system.diagnose_from_array(image)

# ============================================================
# 4. Print results to terminal
# ============================================================

label = result["label"]

print("\n" + "=" * 70)
print("DIAGNOSIS RESULT")
print("=" * 70)

# Color: red for PCOS, green for Normal
if label == "PCOS":
    print(f"\n  \033[91mLabel          : {label}\033[0m")
else:
    print(f"\n  \033[92mLabel          : {label}\033[0m")

print(f"  Ensemble score : {result['ensemble_score']}")
print(f"  CNN probability: {result['cnn_probability']}")
print(f"  Rule score     : {result['rule_score']}")

# Feature values
print("\n  Extracted Features:")
print("  " + "-" * 40)
for feat, val in result["raw_features"].items():
    print(f"    {feat:<30} {val:.4f}")

# Clinical findings (only if PCOS)
if result["clinical_features"]:
    print("\n  Clinical Findings:")
    print("  " + "-" * 40)
    for i, finding in enumerate(result["clinical_features"], 1):
        print(f"    {i}. {finding}")

print("\n" + "=" * 70)

# ============================================================
# 5. Show images as popups
# ============================================================

# --- Input image ---
fig1, ax1 = plt.subplots(figsize=(5, 5))
ax1.imshow(image)
ax1.set_title("Input Image", fontsize=14, fontweight='bold')
ax1.axis("off")
fig1.tight_layout()

# --- LIME image (only if PCOS) ---
if result["cnn_explanation"] and os.path.exists(result["cnn_explanation"]):
    lime_img = cv2.imread(result["cnn_explanation"])
    lime_img = cv2.cvtColor(lime_img, cv2.COLOR_BGR2RGB)

    fig2, ax2 = plt.subplots(figsize=(5, 5))
    ax2.imshow(lime_img)
    ax2.set_title("LIME Explanation", fontsize=14, fontweight='bold')
    ax2.axis("off")
    fig2.tight_layout()

# plt.show() opens ALL figures as popup windows at the same time
plt.show()